### ISSUE TITLE
大佬我报错了 请问这是啥原因呀 驱动都安装了

### ISSUE THREAD

**Issue by fujiakai** [aiguoli/qcourse_scripts#10]
Connected to pydev debugger (build 212.5284.44)
0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频

输入需要的功能：python-BaseException
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\qcourse_scripts\venv\lib\site-packages\playwright\_impl\_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\PycharmProjects\qcourse_scripts\venv\lib\site-packages\playwright\_impl\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\Administrator\PycharmProjects\qcourse_scripts\venv\lib\site-packages\playwright\_impl\_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Chromium distribution 'msedge' is not found at C:\Users\Administrator\AppData\Local\Microsoft\Edge\Application\msedge.exe
Run "npx playwright install msedge"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\qcourse_scripts\venv\lib\site-packages\playwright\_impl\_browser_type.py", line 89, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
playwright._impl._api_types.Error: 
================================================================================
"chromium" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================

Process finished with exit code 1

**Comment by aiguoli** [comment]
执行`playwright install msedge`了吗

**Comment by waterpotter** [comment]
Run "npx playwright install msedge"  先安装edge浏览器
