### ISSUE TITLE
下载失败不知道原因

### ISSUE THREAD

**Issue by Orisland** [aiguoli/qcourse_scripts#15]
环境`mac bigsur`
```python
Traceback (most recent call last):
  File "/Users/zhaolong/qcourse_scripts/qcourse.py", line 138, in <module>
    main()
  File "/Users/zhaolong/qcourse_scripts/qcourse.py", line 132, in main
    asyncio.run(download_selected_chapter(term_id, course_name, chapter_name, courses))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/zhaolong/qcourse_scripts/qcourse.py", line 80, in download_selected_chapter
    urls = get_download_urls(term_id, file_id)
  File "/Users/zhaolong/qcourse_scripts/utils.py", line 218, in get_download_urls
    video_info = get_video_info(file_id, tokens.get('t'), tokens.get('sign'), tokens.get('us'))
AttributeError: 'NoneType' object has no attribute 'get'
zhaolong@Orislands-MacBook-Air qcourse_scripts % 
```

**Comment by GeekTR** [comment]
Traceback (most recent call last):
  File "/Users/tangrui/WorkSpace/qcourse_scripts/qcourse.py", line 138, in <module>
    main()
  File "/Users/tangrui/WorkSpace/qcourse_scripts/qcourse.py", line 116, in main
    asyncio.run(download_selected_chapter(term_id, course_name, chapter_name, courses))
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/tangrui/WorkSpace/qcourse_scripts/qcourse.py", line 80, in download_selected_chapter
    urls = get_download_urls(term_id, file_id)
  File "/Users/tangrui/WorkSpace/qcourse_scripts/utils.py", line 218, in get_download_urls
    video_info = get_video_info(file_id, tokens.get('t'), tokens.get('sign'), tokens.get('us'))
  File "/Users/tangrui/WorkSpace/qcourse_scripts/utils.py", line 166, in get_video_info
    response = requests.get(url, params=params, cookies=load_json_cookies()).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/usr/local/lib/python3.9/site-packages/httpx/_client.py:2003: UserWarning: Unclosed <httpx.AsyncClient object at 0x10a5daca0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

**Comment by GeekTR** [comment]
感觉和你的这个一样啊

**Comment by aiguoli** [comment]
试试新版本代码，已经改过了

**Comment by yyuanshuai** [comment]
> 试试新版本代码，已经改过了

我也是python3.9, 一样的报错。已拉最新代码， 逼我去学python吗：）

**Comment by aiguoli** [comment]
@BurstLinker996 

删掉`cookies.json`试试，可能是cookies文件里的账号没有这节课

**Comment by girlfriendnotfoundexcept** [comment]
我也是一样
Traceback (most recent call last):
  File "qcourse.py", line 154, in <module>
    main()
  File "qcourse.py", line 101, in main
    qq_course.login()
  File "qcourse.py", line 35, in login
    cj = browser_cookie3.edge(domain_name='ke.qq.com')
  File "C:\Users\wangJun\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\browser_cookie3\__init__.py", line 868, in edge
    return Edge(cookie_file, domain_name, key_file).load()
  File "C:\Users\wangJun\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\browser_cookie3\__init__.py", line 556, in __init__
    super().__init__(browser='Edge', cookie_file=cookie_file, domain_name=domain_name, key_file=key_file, **args)
  File "C:\Users\wangJun\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\browser_cookie3\__init__.py", line 229, in __init__
    self.__add_key_and_cookie_file(**kwargs)
  File "C:\Users\wangJun\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\browser_cookie3\__init__.py", line 288, in __add_key_and_cookie_file
    raise BrowserCookieError('Failed to find {} cookie'.format(self.browser))
browser_cookie3.BrowserCookieError: Failed to find Edge cookie

**Comment by bg4vrg** [comment]
我也类似问题。win2019+python3.9

下载单个视频报错如下。下载指定章节只有部分可下。都是已付费的

(qcourse-venv) E:\qcourse_scripts-main>python qcourse.py
0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频
3. 退出登录

输入需要的功能：0
输入课程链接：https://ke.qq.com/webcourse/index.html?r=1671855667622#cid=3485734
Traceback (most recent call last):
  File "E:\qcourse_scripts-main\qcourse.py", line 171, in <module>
    main()
  File "E:\qcourse_scripts-main\qcourse.py", line 123, in main
    asyncio.run(parse_course_url_and_download(course_url))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "E:\qcourse_scripts-main\qcourse.py", line 86, in parse_course_url_and_download
    urls = get_download_url_from_course_url(video_url, -1)
  File "E:\qcourse_scripts-main\utils.py", line 330, in get_download_url_from_course_url
    term_id, file_id = parse_video_url(video_url)
  File "E:\qcourse_scripts-main\utils.py", line 227, in parse_video_url
    file_id = parse_qs(video_url).get('vid')[0]
TypeError: 'NoneType' object is not subscriptable
