### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by tackoolin** [aiguoli/qcourse_scripts#16]
显示如图，

![image](https://user-images.githubusercontent.com/49864354/140010124-bd571bcf-f59e-4268-937f-1cfa39affafb.png)
Traceback (most recent call last):
  File "E:\qcourse_scripts-main\qcourse.py", line 138, in <module>
    main()
  File "E:\qcourse_scripts-main\qcourse.py", line 132, in main
    asyncio.run(download_selected_chapter(term_id, course_name, chapter_name, courses))
  File "C:\Users\lin\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\qcourse_scripts-main\qcourse.py", line 80, in download_selected_chapter
    urls = get_download_urls(term_id, file_id)
  File "E:\qcourse_scripts-main\utils.py", line 218, in get_download_urls
    video_info = get_video_info(file_id, tokens.get('t'), tokens.get('sign'), tokens.get('us'))
AttributeError: 'NoneType' object has no attribute 'get'
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<download_single() done, defined at E:\qcourse_scripts-main\downloader.py:76> exception=ValueError('Incorrect AES key length (31 bytes)')>
Traceback (most recent call last):
  File "E:\qcourse_scripts-main\downloader.py", line 82, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "E:\qcourse_scripts-main\downloader.py", line 26, in decrypt_file
    dec = decrypt(ciphertext, key)
  File "E:\qcourse_scripts-main\downloader.py", line 18, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (31 bytes)
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<download_single() done, defined at E:\qcourse_scripts-main\downloader.py:76> exception=ValueError('Incorrect AES key length (31 bytes)')>
Traceback (most recent call last):
  File "E:\qcourse_scripts-main\downloader.py", line 82, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "E:\qcourse_scripts-main\downloader.py", line 26, in decrypt_file
    dec = decrypt(ciphertext, key)
  File "E:\qcourse_scripts-main\downloader.py", line 18, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (31 bytes)
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<download_single() done, defined at E:\qcourse_scripts-main\downloader.py:76> exception=ValueError('Incorrect AES key length (31 bytes)')>
Traceback (most recent call last):
  File "E:\qcourse_scripts-main\downloader.py", line 82, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "E:\qcourse_scripts-main\downloader.py", line 26, in decrypt_file
    dec = decrypt(ciphertext, key)
  File "E:\qcourse_scripts-main\downloader.py", line 18, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (31 bytes)
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<download_single() done, defined at E:\qcourse_scripts-main\downloader.py:76> exception=ValueError('Incorrect AES key length (31 bytes)')>
Traceback (most recent call last):
  File "E:\qcourse_scripts-main\downloader.py", line 82, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "E:\qcourse_scripts-main\downloader.py", line 26, in decrypt_file
    dec = decrypt(ciphertext, key)
  File "E:\qcourse_scripts-main\downloader.py", line 18, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (31 bytes)
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<download_single() done, defined at E:\qcourse_scripts-main\downloader.py:76> exception=ValueError('Incorrect AES key length (31 bytes)')>
Traceback (most recent call last):
  File "E:\qcourse_scripts-main\downloader.py", line 82, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "E:\qcourse_scripts-main\downloader.py", line 26, in decrypt_file
    dec = decrypt(ciphertext, key)
  File "E:\qcourse_scripts-main\downloader.py", line 18, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "E:\qcourse_scripts-main\venv\lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))

**Comment by aiguoli** [comment]
更新好了，快去试试新版本
