### ISSUE TITLE
UnboundLocalError: local variable 'uin' referenced before assignment

### ISSUE THREAD

**Issue by lsdlh** [aiguoli/qcourse_scripts#20]
anaconda python版本3.7.11
====================
Traceback (most recent call last):
  File "qcourse.py", line 140, in <module>
    main()
  File "qcourse.py", line 134, in main
    asyncio.run(download_selected_chapter(term_id, course_name, chapter_name, courses, cid))
  File "D:\ProgramData\Anaconda3\envs\txkt\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\envs\txkt\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "qcourse.py", line 82, in download_selected_chapter
    urls = get_download_urls(term_id, file_id, cid=cid)
  File "D:\down\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 243, in get_download_urls
    return get_video_url(video_info, video_index, cid=cid, term_id=term_id)
  File "D:\down\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 222, in get_video_url
    key_url = get_key_url_from_m3u8(video.get('url')) + '&token=' + get_token_for_key_url(term_id=term_id, cid=cid)
  File "D:\down\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 212, in get_token_for_key_url
    .format(uin=uin, skey=skey, pskey=pskey, plskey=plskey, cid=cid, term_id=term_id)
UnboundLocalError: local variable 'uin' referenced before assignment

**Comment by lsdlh** [comment]
获取的我的cookie并没有这些东西
![image](https://user-images.githubusercontent.com/45959509/149088020-a450c8af-dd41-4650-981b-9a891e2b3d94.png)

**Comment by lsdlh** [comment]
下载有点慢，只有两三m,带宽够，服务器那边问题吗

**Comment by lsdlh** [comment]
视频key获取不到

**Comment by aiguoli** [comment]
删掉`cookies.json`文件，然后重新运行试试。

脚本运行只访问腾讯的服务器，跟宽带没关系

**Comment by Zi-Yi-ZHANG** [comment]
> 

老哥，想问下你这个 UnboundLocalError 的问题是咋解决的啊

**Comment by Zi-Yi-ZHANG** [comment]
> # anaconda python版本3.7.11
> Traceback (most recent call last): File "qcourse.py", line 140, in main() File "qcourse.py", line 134, in main asyncio.run(download_selected_chapter(term_id, course_name, chapter_name, courses, cid)) File "D:\ProgramData\Anaconda3\envs\txkt\lib\asyncio\runners.py", line 43, in run return loop.run_until_complete(main) File "D:\ProgramData\Anaconda3\envs\txkt\lib\asyncio\base_events.py", line 587, in run_until_complete return future.result() File "qcourse.py", line 82, in download_selected_chapter urls = get_download_urls(term_id, file_id, cid=cid) File "D:\down\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 243, in get_download_urls return get_video_url(video_info, video_index, cid=cid, term_id=term_id) File "D:\down\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 222, in get_video_url key_url = get_key_url_from_m3u8(video.get('url')) + '&token=' + get_token_for_key_url(term_id=term_id, cid=cid) File "D:\down\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 212, in get_token_for_key_url .format(uin=uin, skey=skey, pskey=pskey, plskey=plskey, cid=cid, term_id=term_id) UnboundLocalError: local variable 'uin' referenced before assignment

老哥，想问下你这个 UnboundLocalError 的问题是咋解决的啊

**Comment by aiguoli** [comment]
试试新版本的代码吧

**Comment by yyuanshuai** [comment]
> 试试新版本的代码吧

新版本也不行, ,还是这个错误, 救救孩子吧

**Comment by Haoshenqi0123** [comment]
> 

新版本，cookie里找不到clientuin。把clientuin改成p_uin 可以使用。不知道为什么

**Comment by aiguoli** [comment]
行了，新版本解决这玩意了，因为我也遇到了

**Comment by winann** [comment]
Traceback (most recent call last):
  File "qcourse.py", line 162, in <module>
    main()
  File "qcourse.py", line 152, in main
    asyncio.run(
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "qcourse.py", line 92, in download_selected_chapter
    urls = get_download_urls(term_id, file_id, cid=cid)
  File "/Users/Ann/Winann/qcourse_scripts/utils.py", line 281, in get_download_urls
    return get_video_url(video_info, video_index, cid=cid, term_id=term_id)
  File "/Users/Ann/Winann/qcourse_scripts/utils.py", line 253, in get_video_url
    + get_token_for_key_url(term_id=term_id, cid=cid)
  File "/Users/Ann/Winann/qcourse_scripts/utils.py", line 236, in get_token_for_key_url
    uin=uin, skey=skey, pskey=pskey, plskey=plskey, cid=cid, term_id=term_id
UnboundLocalError: local variable 'uin' referenced before assignment


这个问题有遇到吗？使用最新的版本
