### ISSUE TITLE
在pip install -Ur requirements.txt这一步遭遇了不明问题

### ISSUE THREAD

**Issue by BrightMoonInner** [aiguoli/qcourse_scripts#21]
大佬的使用方法非常贴心了，我的python版本是3.10，前面三步均正常，到了第四步这里就

![微信图片_20220115192126](https://user-images.githubusercontent.com/88758484/149619909-ca8e7393-717d-4948-b1b7-3394f7aba24b.png)

(qcourse-venv) C:\Users\l4115\Desktop\qcourse_scripts-main>pip install -Ur requirements.txt
Collecting aiohttp
  Downloading aiohttp-3.8.1-cp310-cp310-win_amd64.whl (555 kB)
     |████████████████████████████████| 555 kB 168 kB/s
Collecting anyio==3.3.0
  Downloading anyio-3.3.0-py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 204 kB/s
Collecting async-timeout==3.0.1
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs==21.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 231 kB/s
Collecting certifi==2020.12.5
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 159 kB/s
Collecting chardet==4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 159 kB/s
Collecting charset-normalizer==2.0.4
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting greenlet==1.1.0
  Downloading greenlet-1.1.0.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 157 kB/s
Collecting h11==0.12.0
  Downloading h11-0.12.0-py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 196 kB/s
Collecting httpcore==0.13.6
  Downloading httpcore-0.13.6-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 78 kB/s
Collecting httpx==0.19.0
  Downloading httpx-0.19.0-py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 97 kB/s
Collecting idna==2.10
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 114 kB/s
Collecting multidict==5.1.0
  Downloading multidict-5.1.0.tar.gz (53 kB)
     |████████████████████████████████| 53 kB 74 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting Pillow==8.2.0
  Downloading Pillow-8.2.0.tar.gz (47.9 MB)
     |████████████████████████████████| 47.9 MB 28 kB/s
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/playwright/
Collecting playwright==1.13.1
  Downloading playwright-1.13.1-py3-none-win_amd64.whl (15.2 MB)
     |████████████████████████████████| 15.2 MB 84 kB/s
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pycryptodome/
Collecting pycryptodome==3.10.1
  Downloading pycryptodome-3.10.1-cp35-abi3-win_amd64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 79 kB/s
Collecting pyee==8.1.0
  Downloading pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 87 kB/s
Collecting rfc3986==1.5.0
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting six==1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting sniffio==1.2.0
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting typing-extensions==3.10.0.0
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting urllib3==1.26.4
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 52 kB/s
Collecting websockets==9.1
  Downloading websockets-9.1.tar.gz (76 kB)
     |████████████████████████████████| 76 kB 58 kB/s
Collecting wincertstore==0.2
  Downloading wincertstore-0.2-py2.py3-none-any.whl (8.8 kB)
Collecting yarl==1.6.3
  Downloading yarl-1.6.3.tar.gz (176 kB)
     |████████████████████████████████| 176 kB 49 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting aiohttp
  Downloading aiohttp-3.8.0-cp310-cp310-win_amd64.whl (571 kB)
     |████████████████████████████████| 571 kB 69 kB/s
  Downloading aiohttp-3.7.4.post0.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 65 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Using legacy 'setup.py install' for websockets, since package 'wheel' is not installed.
Building wheels for collected packages: multidict, yarl, aiohttp
  Building wheel for multidict (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\Scripts\python.exe' 'C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\l4115\AppData\Local\Temp\tmpbz0a8qua'
       cwd: C:\Users\l4115\AppData\Local\Temp\pip-install-6kwf7fgq\multidict_d1498c5ac0524aff8124cbed94a2c140
  Complete output (93 lines):
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\multidict
  copying multidict\_abc.py -> build\lib.win-amd64-3.10\multidict
  copying multidict\_compat.py -> build\lib.win-amd64-3.10\multidict
  copying multidict\_multidict_base.py -> build\lib.win-amd64-3.10\multidict
  copying multidict\_multidict_py.py -> build\lib.win-amd64-3.10\multidict
  copying multidict\__init__.py -> build\lib.win-amd64-3.10\multidict
  running egg_info
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict\_multidict.html'
  warning: no previously-included files found matching 'multidict\*.so'
  warning: no previously-included files found matching 'multidict\*.pyd'
  warning: no previously-included files found matching 'multidict\*.pyd'
  no previously-included directories found matching 'docs\_build'
  writing manifest file 'multidict.egg-info\SOURCES.txt'
  copying multidict\__init__.pyi -> build\lib.win-amd64-3.10\multidict
  copying multidict\_multidict.c -> build\lib.win-amd64-3.10\multidict
  copying multidict\py.typed -> build\lib.win-amd64-3.10\multidict
  creating build\lib.win-amd64-3.10\multidict\_multilib
  copying multidict\_multilib\defs.h -> build\lib.win-amd64-3.10\multidict\_multilib
  copying multidict\_multilib\dict.h -> build\lib.win-amd64-3.10\multidict\_multilib
  copying multidict\_multilib\istr.h -> build\lib.win-amd64-3.10\multidict\_multilib
  copying multidict\_multilib\iter.h -> build\lib.win-amd64-3.10\multidict\_multilib
  copying multidict\_multilib\pair_list.h -> build\lib.win-amd64-3.10\multidict\_multilib
  copying multidict\_multilib\views.h -> build\lib.win-amd64-3.10\multidict\_multilib
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 91, in <module>
      setup(ext_modules=extensions, **args)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-nf9ik68x\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for multidict
  Building wheel for yarl (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\Scripts\python.exe' 'C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\l4115\AppData\Local\Temp\tmpuojmmu2_'
       cwd: C:\Users\l4115\AppData\Local\Temp\pip-install-6kwf7fgq\yarl_be64a5db3e5b47ce9114590f9b16ecb0
  Complete output (87 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\yarl
  copying yarl\_quoting.py -> build\lib.win-amd64-3.10\yarl
  copying yarl\_quoting_py.py -> build\lib.win-amd64-3.10\yarl
  copying yarl\_url.py -> build\lib.win-amd64-3.10\yarl
  copying yarl\__init__.py -> build\lib.win-amd64-3.10\yarl
  running egg_info
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl\*.html'
  warning: no previously-included files found matching 'yarl\*.so'
  warning: no previously-included files found matching 'yarl\*.pyd'
  no previously-included directories found matching 'docs\_build'
  writing manifest file 'yarl.egg-info\SOURCES.txt'
  copying yarl\__init__.pyi -> build\lib.win-amd64-3.10\yarl
  copying yarl\_quoting_c.c -> build\lib.win-amd64-3.10\yarl
  copying yarl\_quoting_c.pyi -> build\lib.win-amd64-3.10\yarl
  copying yarl\_quoting_c.pyx -> build\lib.win-amd64-3.10\yarl
  copying yarl\py.typed -> build\lib.win-amd64-3.10\yarl
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 78, in <module>
      setup(ext_modules=extensions, **args)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\l4115\AppData\Local\Temp\pip-build-env-yun190pn\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for yarl
  Building wheel for aiohttp (PEP 517) ... done
  Created wheel for aiohttp: filename=aiohttp-3.7.4.post0-py3-none-any.whl size=451945 sha256=6cc6964f0350eaa1a9785817cae14b281afd85d2409e0f170c48929181dab111
  Stored in directory: c:\users\l4115\appdata\local\pip\cache\wheels\fc\84\e0\52113c57eb9b09b6b187a0f369eaad6fc7fc64bb7247c83b89
Successfully built aiohttp
Failed to build multidict yarl
ERROR: Could not build wheels for multidict, yarl which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse-venv\Scripts\python.exe -m pip install --upgrade pip' command.

然后我试图去做第五步，

(qcourse-venv) C:\Users\l4115\Desktop\qcourse_scripts-main>playwright install msedge
'playwright' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

然后是试图第六，

(qcourse-venv) C:\Users\l4115\Desktop\qcourse_scripts-main>python qcourse.py
Traceback (most recent call last):
  File "C:\Users\l4115\Desktop\qcourse_scripts-main\qcourse.py", line 7, in <module>
    from playwright.sync_api import sync_playwright
ModuleNotFoundError: No module named 'playwright'

(qcourse-venv) C:\Users\l4115\Desktop\qcourse_scripts-main>

**Comment by aiguoli** [comment]
猜测你这是playwright没有正确安装，二选一
- 永久换源
```shell
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

pip install -Ur requirements.txt

```
- 临时换源
`pip install -i https://pypi.tuna.tsinghua.edu.cn/simple playwright`
