### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by codingboylj** [aiguoli/qcourse_scripts#25]
```
$ python qcourse.py
0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频

输入需要的功能：2
请输入课程cid:310478
Traceback (most recent call last):
  File "D:\Downloads\qcourse_scripts\qcourse.py", line 140, in <module>
    main()
  File "D:\Downloads\qcourse_scripts\qcourse.py", line 121, in main
    course_name = get_course_from_api(cid)
  File "D:\Downloads\qcourse_scripts\utils.py", line 20, in get_course_from_api
    name = response.get('result').get('course_detail').get('name').replace('/', '／').replace('\\', '＼')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by aiguoli** [comment]
注意，得是你账号里有的才可以，点[个人中心](https://ke.qq.com/user/index)看下是不是没有添加

**Comment by codingboylj** [comment]
我的个人中心里是有这节课的
![Screenshot_2022-04-06-15-44-48-011_com kiwibrowser browser](https://user-images.githubusercontent.com/57084184/161922614-32db97cd-a135-4629-b944-644a71df9856.jpg)
