### ISSUE TITLE
NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by lenngennd** [aiguoli/qcourse_scripts#26]
(qcourse-venv) PS D:\qcourse_scripts-main> python qcourse.py
0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频

输入需要的功能：1
请输入课程cid:3138704
Traceback (most recent call last):
  File "D:\qcourse_scripts-main\qcourse.py", line 140, in <module>
    main()
  File "D:\qcourse_scripts-main\qcourse.py", line 105, in main
    course_name = get_course_from_api(cid)
  File "D:\qcourse_scripts-main\utils.py", line 20, in get_course_from_api
    name = response.get('result').get('course_detail').get('name').replace('/', '／').replace('\\', '＼')
AttributeError: 'NoneType' object has no attribute 'get'
(qcourse-venv) PS D:\qcourse_scripts-main>

**Comment by lenngennd** [comment]
(qcourse-venv) PS D:\qcourse_scripts-main> python qcourse.py
0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频

输入需要的功能：0
输入课程链接：https://ke.qq.com/webcourse/3138704/103263921#taid=12641763792512144&vid=387702295243560551
D:\qcourse_scripts-main\qcourse.py:102: RuntimeWarning: coroutine 'parse_course_url_and_download' was never awaited
  parse_course_url_and_download(course_url)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
(qcourse-venv) PS D:\qcourse_scripts-main>

**Comment by lenngennd** [comment]
(qcourse-venv) PS D:\qcourse_scripts-main> python qcourse.py
0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频

输入需要的功能：2
请输入课程cid:3138704
Traceback (most recent call last):
  File "D:\qcourse_scripts-main\qcourse.py", line 140, in <module>
    main()
  File "D:\qcourse_scripts-main\qcourse.py", line 121, in main
    course_name = get_course_from_api(cid)
  File "D:\qcourse_scripts-main\utils.py", line 20, in get_course_from_api
    name = response.get('result').get('course_detail').get('name').replace('/', '／').replace('\\', '＼')
AttributeError: 'NoneType' object has no attribute 'get'
(qcourse-venv) PS D:\qcourse_scripts-main>

**Comment by Diaosi1111** [comment]
单个视频下载你可是试一下新的pr里的版本

**Comment by lenngennd** [comment]
> 单个视频下载你可是试一下新的pr里的版本

对 用的源码最新的版本

**Comment by Diaosi1111** [comment]
#27 尝试一下这个

**Comment by aiguoli** [comment]
已经merge新pr了，直接拉新的代码试试看

**Comment by lenngennd** [comment]
> 已经merge新pr了，直接拉新的代码试试看
输入课程链接：https://ke.qq.com/webcourse/3138704/103263921#taid=12641763792512144&vid=387702295243560551
Traceback (most recent call last):
  File "D:\qcourse_scripts-main\qcourse.py", line 162, in <module>
    main()
  File "D:\qcourse_scripts-main\qcourse.py", line 118, in main
    asyncio.run(parse_course_url_and_download(course_url))
  File "C:\Users\MYTHOS\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\MYTHOS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\qcourse_scripts-main\qcourse.py", line 78, in parse_course_url_and_download
    urls = get_download_url_from_course_url(video_url, -1)
  File "D:\qcourse_scripts-main\utils.py", line 277, in get_download_url_from_course_url
    return get_video_url(video_info, video_index, cid=cid, term_id=term_id)
  File "D:\qcourse_scripts-main\utils.py", line 257, in get_video_url
    + get_token_for_key_url(term_id=term_id, cid=cid)
  File "D:\qcourse_scripts-main\utils.py", line 240, in get_token_for_key_url
    uin=uin, skey=skey, pskey=pskey, plskey=plskey, cid=cid, term_id=term_id
UnboundLocalError: local variable 'uin' referenced before assignment
(qcourse-venv) PS D:\qcourse_scripts-main>

**Comment by Diaosi1111** [comment]
暂不推荐微信登陆，api不一样好像
