### ISSUE TITLE
check_hostname requires Windows python3.9 

### ISSUE THREAD

**Issue by Haoshenqi0123** [aiguoli/qcourse_scripts#28]
Traceback (most recent call last):
  File "D:\study\3\qcourse_scripts\qcourse.py", line 162, in <module>
    main()
  File "D:\study\3\qcourse_scripts\qcourse.py", line 118, in main
    asyncio.run(parse_course_url_and_download(course_url))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\study\3\qcourse_scripts\qcourse.py", line 78, in parse_course_url_and_download
    urls = get_download_url_from_course_url(video_url, -1)
  File "D:\study\3\qcourse_scripts\utils.py", line 273, in get_download_url_from_course_url
    tokens = get_video_token(term_id, file_id)
  File "D:\study\3\qcourse_scripts\utils.py", line 198, in get_video_token
    response = requests.get(
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\study\3\qcourse_scripts\qcourse-venv\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by aiguoli** [comment]
不要用魔法，关掉或者开PAC模式

**Comment by Haoshenqi0123** [comment]
> 
感谢🙏，已经解决了
