### ISSUE TITLE
依赖已安装，运行报错

### ISSUE THREAD

**Issue by EndlessJY** [aiguoli/qcourse_scripts#3]
windows10环境：
获取课程信息成功,准备下载！
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\qcourse_scripts-main\qcourse.py", line 147, in <module>
    main()
  File "C:\Users\xxx\Desktop\qcourse_scripts-main\qcourse.py", line 130, in main
    qq_course = QCourse()
  File "C:\Users\xxx\Desktop\qcourse_scripts-main\qcourse.py", line 32, in __init__
    self.driver = Edge(executable_path='msedgedriver.exe', options=self.options)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\msedge\selenium_tools\webdriver.py", line 103, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find MSEdge binary

**Comment by EndlessJY** [comment]
已解决，未安装相应浏览器
