### ISSUE TITLE
下载单个视频出错

### ISSUE THREAD

**Issue by lingfantang** [aiguoli/qcourse_scripts#31]
`输入课程链接：https://ke.qq.com/webcourse/4355298/104519918#taid=45766197&lite=1&vid=387702296971725976
dad1ae2e-aac8-11ec-aa00-98fa9b0b8394 开始下载
Traceback (most recent call last):
  File "D:\A\qcourse_scripts\qcourse.py", line 162, in <module>
    main()
  File "D:\A\qcourse_scripts\qcourse.py", line 118, in main
    asyncio.run(parse_course_url_and_download(course_url))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\A\qcourse_scripts\qcourse.py", line 80, in parse_course_url_and_download
    await download_single(urls[0], urls[1], filename, path)
  File "D:\A\qcourse_scripts\downloader.py", line 149, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "D:\A\qcourse_scripts\downloader.py", line 27, in decrypt_file
    dec = decrypt(ciphertext, key)
  File "D:\A\qcourse_scripts\downloader.py", line 20, in decrypt
    plaintext = cipher.decrypt(ciphertext[AES.block_size :])
  File "D:\A\qcourse_scripts\qcourse-venv\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode`
试了下其他两个功能，课程回放批量下载应该不支持？于是手动单个视频下载。。
貌似只有这个上面链接会出问题，该课程其他回放正常下载并转码（只是最后说shell出现异常

**Comment by aiguoli** [comment]
回放课程需要在老师设置的有效期内下载；

shell出现异常的问题不用理，视频能播放就行。

**Comment by lingfantang** [comment]
> 回放课程需要在老师设置的有效期内下载；
> 
> shell出现异常的问题不用理，视频能播放就行。

不不不，不是课程有效期的问题，应该是无法生成下载的链接。
上面这个链接在当时是没过期的，试试下面这个链接，是一样的问题。（只有5天过期了。。
```
0. 下载单个视频
1. 下载课程指定章节
2. 下载课程全部视频

输入需要的功能：0
输入课程链接：https://ke.qq.com/webcourse/4355298/104519918#taid=48016799&lite=1&vid=387702297875174893
79d329b5-d3fd-11ec-87d5-98fa9b0b8394 开始下载
Traceback (most recent call last):
  File "D:\Apps\Git\qcourse_scripts\qcourse.py", line 162, in <module>
    main()
  File "D:\Apps\Git\qcourse_scripts\qcourse.py", line 118, in main
    asyncio.run(parse_course_url_and_download(course_url))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Apps\Git\qcourse_scripts\qcourse.py", line 80, in parse_course_url_and_download
    await download_single(urls[0], urls[1], filename, path)
  File "D:\Apps\Git\qcourse_scripts\downloader.py", line 149, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "D:\Apps\Git\qcourse_scripts\downloader.py", line 27, in decrypt_file
    dec = decrypt(ciphertext, key)
  File "D:\Apps\Git\qcourse_scripts\downloader.py", line 20, in decrypt
    plaintext = cipher.decrypt(ciphertext[AES.block_size :])
  File "D:\Apps\Git\qcourse_scripts\qcourse-venv\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```
