### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by adminlove520** [aiguoli/qcourse_scripts#32]
Traceback (most recent call last):
  File "qcourse.py", line 162, in <module>
    main()
  File "qcourse.py", line 152, in main
    asyncio.run(
  File "F:\python3.8.5\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "F:\python3.8.5\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "qcourse.py", line 92, in download_selected_chapter
    urls = get_download_urls(term_id, file_id, cid=cid)
  File "C:\Users\xx\Downloads\qcourse_scripts-main\utils.py", line 281, in get_download_urls
    return get_video_url(video_info, video_index, cid=cid, term_id=term_id)
  File "C:\Users\xx\Downloads\qcourse_scripts-main\utils.py", line 253, in get_video_url
    + get_token_for_key_url(term_id=term_id, cid=cid)
  File "C:\Users\xx\Downloads\qcourse_scripts-main\utils.py", line 236, in get_token_for_key_url
    uin=uin, skey=skey, pskey=pskey, plskey=plskey, cid=cid, term_id=term_id
UnboundLocalError: local variable 'uin' referenced before assignment

报这个错误，这是什么原因呀  拉取的最新代码的

**Comment by aiguoli** [comment]
最新版本解决了获取不到uin的问题，支持手动输入了

**Comment by adminlove520** [comment]
目前我在尝试能不能微信账号通过绑定qq来解决这个问题

**Comment by adminlove520** [comment]
无法获取到uin，请输入你的QQ：1487173844
[06/Apr/2022 23:41:20] INFO - p_lskey: None, ptui_loginuin: 1487173844, skey: None, p_skey: None
规范精讲22年 开课准备及复习要点 开始下载
E:\personal\net\lib\site-packages\httpx\_client.py:2003: UserWarning: Unclosed <httpx.AsyncClient object at 0x056FB0A0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
  warnings.warn(
Traceback (most recent call last):
  File "qcourse.py", line 165, in <module>
    main()
  File "qcourse.py", line 155, in main
    asyncio.run(
  File "E:\personal\net\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "E:\personal\net\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "qcourse.py", line 92, in download_selected_chapter
    urls = get_download_urls(term_id, file_id, cid=cid)
  File "D:\project\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 284, in get_download_urls
    video_info = get_video_info(
  File "D:\project\qcourse_scripts-main\qcourse_scripts-main\utils.py", line 211, in get_video_info
    response = requests.get(url, params=params, cookies=load_json_cookies()).json()
  File "E:\personal\net\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "E:\personal\net\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "E:\personal\net\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\personal\net\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
