### ISSUE TITLE
打开浏览后，自动关闭

### ISSUE THREAD

**Issue by th8664484** [aiguoli/qcourse_scripts#43]
输入需要的功能：0
Traceback (most recent call last):
  File "E:\python\qcourse_scripts\qcourse.py", line 169, in <module>
    main()
  File "E:\python\qcourse_scripts\qcourse.py", line 115, in main
    qq_course.login()
  File "E:\python\qcourse_scripts\qcourse.py", line 40, in login
    page.click('#js_login')
  File "E:\python\qcourse_scripts\qcourse-venv\lib\site-packages\playwright\sync_api\_generated.py", line 6791, in click
    self._sync(
  File "E:\python\qcourse_scripts\qcourse-venv\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "E:\python\qcourse_scripts\qcourse-venv\lib\site-packages\playwright\_impl\_page.py", line 586, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "E:\python\qcourse_scripts\qcourse-venv\lib\site-packages\playwright\_impl\_frame.py", line 403, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "E:\python\qcourse_scripts\qcourse-venv\lib\site-packages\playwright\_impl\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "E:\python\qcourse_scripts\qcourse-venv\lib\site-packages\playwright\_impl\_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
======== logs ====
waiting for selector "#js_login"
  selector resolved to hidden <a id="js_login" rel="nofollow" data-hook="login" h…>登录</a>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not visible - waiting...

**Comment by th8664484** [comment]
(qcourse-venv) E:\python\qcourse_scripts>(node:9012) UnhandledPromiseRejectionWarning: Error
    at assert (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\utils\utils.js:250:21)
    at CRSession._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:220:25)
    at CRConnection._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:111:26)
    at Immediate.<anonymous> (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\pipeTransport.js:71:42)
    at processImmediate (internal/timers.js:461:21)
(node:9012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9012) UnhandledPromiseRejectionWarning: Error
    at assert (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\utils\utils.js:250:21)
    at CRSession._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:220:25)
    at CRConnection._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:111:26)
    at Immediate.<anonymous> (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\pipeTransport.js:71:42)
    at processImmediate (internal/timers.js:461:21)
(node:9012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9012) UnhandledPromiseRejectionWarning: Error
    at assert (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\utils\utils.js:250:21)
    at CRSession._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:220:25)
    at CRConnection._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:111:26)
    at Immediate.<anonymous> (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\pipeTransport.js:81:44)
    at processImmediate (internal/timers.js:461:21)
(node:9012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:9012) UnhandledPromiseRejectionWarning: Error
    at assert (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\utils\utils.js:250:21)
    at CRSession._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:220:25)
    at CRConnection._onMessage (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\chromium\crConnection.js:111:26)
    at Immediate.<anonymous> (E:\python\qcourse_scripts\qcourse-venv\Lib\site-packages\playwright\driver\package\lib\server\pipeTransport.js:81:44)
    at processImmediate (internal/timers.js:461:21)
(node:9012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by stoneJava** [comment]
哥们，解决了没？我也遇到了同样的问题

**Comment by aiguoli** [comment]
解决了，去掉了playwright依赖，下载新版本，然后按照readme的内容操作就行了
