### ISSUE TITLE
下载购买的收费课程报错

### ISSUE THREAD

**Issue by jiguanlang** [aiguoli/qcourse_scripts#44]
Traceback (most recent call last):
  File "D:\qcourse_scripts\qcourse-venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\qcourse_scripts\qcourse.py", line 154, in <module>
    main()
  File "D:\qcourse_scripts\qcourse.py", line 123, in main
    asyncio.run(
  File "C:\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\qcourse_scripts\qcourse.py", line 80, in download_selected_chapter
    urls = get_download_urls(term_id, file_id, cid=cid)
  File "D:\qcourse_scripts\utils.py", line 345, in get_download_urls
    video_info = get_video_info(
  File "D:\qcourse_scripts\utils.py", line 258, in get_video_info
    response = requests.get(url, params=params, cookies=load_json_cookies(), proxies=PROXIES).json()
  File "D:\qcourse_scripts\qcourse-venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by destiny-110** [comment]
这个可以下载腾讯课堂收费课程吗
