### ISSUE TITLE
下载报错TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by sunjinkkk** [aiguoli/qcourse_scripts#45]
下载全部课程视频时报错
```
请输入要下载的课程序号(回车结束)：1
获取课程信息成功,准备下载！
Traceback (most recent call last):
  File "qcourse.py", line 154, in <module>
    main()
  File "qcourse.py", line 131, in main
    logger.info('cid: '+cid)
TypeError: can only concatenate str (not "int") to str
```

**Comment by aiguoli** [comment]
修复了，腾讯课堂这个地方之前可能是返回的字符串，现在变成int了
