### ISSUE TITLE
是不是不能下载购买了的视频

### ISSUE THREAD

**Issue by oper1000** [aiguoli/qcourse_scripts#56]
#55 问题已经解决了。

然后，发现收费的视频无法下载，log里面报错：
Incorrect AES key length (39 bytes)

完整日志：

`2022-11-28 20:07:31,902 - INFO - cid: 453949
2022-11-28 20:07:41,608 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-9' coro=<download_single() done, defined at D:\qcourse_scripts-main\downloader.py:138> exception=ValueError('Incorrect AES key length (39 bytes)')>
Traceback (most recent call last):
  File "D:\qcourse_scripts-main\downloader.py", line 150, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "D:\qcourse_scripts-main\downloader.py", line 28, in decrypt_file
    dec = decrypt(ciphertext, key)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\downloader.py", line 20, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (39 bytes)
2022-11-28 20:07:45,755 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<download_single() done, defined at D:\qcourse_scripts-main\downloader.py:138> exception=ValueError('Incorrect AES key length (39 bytes)')>
Traceback (most recent call last):
  File "D:\qcourse_scripts-main\downloader.py", line 150, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "D:\qcourse_scripts-main\downloader.py", line 28, in decrypt_file
    dec = decrypt(ciphertext, key)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\downloader.py", line 20, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (39 bytes)
2022-11-28 20:07:45,757 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-18' coro=<download_single() done, defined at D:\qcourse_scripts-main\downloader.py:138> exception=ValueError('Incorrect AES key length (39 bytes)')>
Traceback (most recent call last):
  File "D:\qcourse_scripts-main\downloader.py", line 150, in download_single
    decrypt_file(str(file) + '.ts', key)
  File "D:\qcourse_scripts-main\downloader.py", line 28, in decrypt_file
    dec = decrypt(ciphertext, key)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\downloader.py", line 20, in decrypt
    cipher = AES.new(key, AES.MODE_CBC, iv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qcourse_scripts-main\qcourse-venv\Lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (39 bytes)
2022-11-28 20:07:45,757 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<download_single() done, defined at D:\qcourse_scripts-main\downloader.py:138> exception=ValueError('Incorrect AES key length (39 bytes)')>
Traceback (most recent call last):
  File "D:\qcourse_scripts-main\downloader.py", line 150, in download_single`

所以请问是不是不能下载收费的视频，因为我试了一下免费的视频是可以下载的。

**Comment by aiguoli** [comment]
只要是你能在网页看的就都能下载，我看好多人报这个错，可以提供一下出现问题的课程链接吗

**Comment by oper1000** [comment]
> 只要是你能在网页看的就都能下载，我看好多人报这个错，可以提供一下出现问题的课程链接吗

https://ke.qq.com/course/453949#term_id=106050366

这个是收费课程！我不确定其他人是否能打开！

**Comment by aiguoli** [comment]
能打开，但是4799元，太贵了

**Comment by oper1000** [comment]
那能下载吗？
