### ISSUE TITLE
what happened,what should I do

### ISSUE THREAD

**Issue by BrightMoonInner** [aiguoli/qcourse_scripts#6]
Traceback (most recent call last):
  File "D:/Users/Desktop/qcourse_scripts-main/qcourse.py", line 153, in <module>
    main()
  File "D:/Users/Desktop/qcourse_scripts-main/qcourse.py", line 103, in main
    qq_course = QCourse()
  File "D:/Users/Desktop/qcourse_scripts-main/qcourse.py", line 32, in __init__
    self.driver = Edge(executable_path='msedgedriver.exe', options=self.options)
  File "D:\Program Files\Python38\lib\site-packages\msedge\selenium_tools\webdriver.py", line 103, in __init__
    RemoteWebDriver.__init__(
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find MSEdge binary

Process finished with exit code 1

**Comment by aiguoli** [comment]
the script has been updated, check it 😀
