### ISSUE TITLE
出现TypeError，请问怎么解决

### ISSUE THREAD

**Issue by galaxyq** [aiguoli/qcourse_scripts#60]
获取课程信息成功,准备下载！
Traceback (most recent call last):
  File "D:\★Tools\QD\Download\qcourse_scripts-main\qcourse.py", line 171, in <module>
    main()
  File "D:\★Tools\QD\Download\qcourse_scripts-main\qcourse.py", line 148, in main
    logger.info('cid: '+cid)
TypeError: can only concatenate str (not "int") to str

**Comment by qianyingshuo** [comment]
你去找到qcourse.py 文件的148行，先把这句logger注释掉，然后就能正常使用。我不懂python，但是作者这句应该是在打印日志。不关键。具体等着作者修理。

**Comment by aiguoli** [comment]
#58 相同问题，已解决
